mysite/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings

from django.contrib import admin
from mysite.forms import WableAuthenticationForm
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.index', name='index'),
    url(r'^modelform_example/(?P<user_id>\d+)/$', 'mysite.views.modelform_example', name='frag_form'),
    url(r'^modelform_example/$', 'mysite.views.modelform_example', name='modelform_example'),
       
    url(r'^register/$', 'mysite.views.register', name='register'),
    url(r'^profile/$', 'mysite.views.profile', name='profile'),
    url(r'^login/', 'django.contrib.auth.views.login', {"template_name": "login.html", 'authentication_form': WableAuthenticationForm}),
    url(r'^logout/', 'django.contrib.auth.views.logout_then_login', {"login_url": "/login/"}),
    url(r'^admin/', include(admin.site.urls)), 
    url(r'^municipios_app/', include('municipios.urls')),

)
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from image_cropping.fields import ImageRatioField, ImageCropField
from django.contrib.auth.models import User
from municipios.models import Municipio
    
class EstablishmentType(models.Model):
    name_type = models.CharField(u'Tipo do Estabelecimento', null=False, max_length=100)
    def __unicode__(self):
        return self.name_type
         
class Establishment(models.Model):
    user = models.ForeignKey(User, related_name='ec_user')
    address = models.OneToOneField(Municipio, related_name='ec_address')
    ec_type = models.OneToOneField(EstablishmentType, related_name='ec_type')
    name = models.CharField(u'Nome do Estabelecimento', null=False, max_length=100)
    img_logo = models.ImageField(upload_to='establishmet/', blank=False, null=True)
    img_vitrin = models.ImageField(upload_to='establishmet/', blank=False, null=True)
    cnpj = models.CharField(u'Cnpj', null=True, max_length=40)
    insc_est = models.CharField(u'Insc. Estadual', null=True, max_length=40)
    phone = models.CharField(u'Telefone', null=False, max_length=50)
    site = models.URLField(u'Site', null=True, max_length=80)
    email = models.EmailField(u'E-mail', null=False, max_length=100)
    zip_code = models.CharField(u'Cep', null=False, max_length=20)
    
    def __unicode__(self):
        return self.nome
    
class UserProfile(models.Model):    
    user = models.OneToOneField(User, related_name='user_profile')
    image_field = models.ImageField(upload_to='profile/', blank=False, null=True)  
    phone = models.CharField(u'Telefone', null=False, max_length=50)
    birthday = models.DateField(u'Nascimento', null=True)
    address = models.OneToOneField(Municipio, related_name='user_address')

    def __unicode__(self):
        return self.user.username
    

class Image(models.Model):
    image_field = ImageCropField(upload_to='image/', blank=False)    
    cropping_free = ImageRatioField('image_field', '200x100', free_crop=False, size_warning=True, verbose_name='')

    def get_cropping_as_list(self):
        if self.cropping:
            return list(map(int, self.cropping.split(',')))

templates/base.html
{% load staticfiles %}
{% load cropping %}
{% load url from future %}
<!DOCTYPE html>
<html>
  <head>
      <!-- Bootstrap Core CSS -->
	<!-- Optional theme -->
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" id="bs-css">
	<link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
	
	<link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">	

    
    <title>Image cropping example {% block title %}{% endblock %}</title>
    <style type="text/css">
      th {text-align: left;}
      #navigation li {
        display: inline;
        list-style-type: none;
        padding-right: 10px;
      }
      article, aside, figure, footer, header, hgroup, 
  	  menu, nav, section { display: block; }
    </style>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block content %}
    <input class="datepicker" data-date-format="mm/dd/yyyy">
    {% endblock %}
  </body>
  <script src="{% static "js/jquery.min.js" %}"></script>
   <!-- Latest compiled and minified JavaScript -->
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/bootstrap-filestyle.min.js" %}"></script>
  <script src="{% static "js/jquery-ui.min.js" %}"></script>
  <script src="{% static "js/jquery.form.js" %}"></script>
  <script src="{% static "js/jquery.form.min.js" %}"></script>
  <script src="{% static "js/jquery.maskedinput.js" %}"></script>

  <script type="text/javascript">

 	//Stle for input file
  	$("#file_profile").filestyle({buttonBefore: true, buttonName: "btn-primary", buttonText: "Imagem", input: false});
  	$(":file").filestyle({buttonBefore: true, buttonName: "btn-primary", buttonText: "Adicionar Imagem"});
  	
  	
    //Masks for inputs
    $(function() {
        $.mask.definitions['~'] = "[+-]";
        $("#date").mask("99/99/9999", {autoclear: false});
        $("#id_birthday").mask("99/99/9999", {autoclear: false});
        $("#phone").mask("(99) 9999-99999", {autoclear: false});
        $("#id_phone").mask("(99) 9999-99999", {autoclear: false});
        $("input").blur(function() {
            $("#info").html("Unmasked value: " + $(this).mask());
        }).dblclick(function() {
            $(this).unmask();
        });
    });
  	
  	//Function for input file
 	function readURL(input) {  		
        if (input.files && input.files[0]) {        	
            var reader = new FileReader();
            reader.onload = function (e) { 
                //Submit form
               /*  $("#cropping_form").submit(); */
              
            };
            reader.readAsDataURL(input.files[0]);
        }
    } 
 	function readFile(input) {  		
        if (input.files && input.files[0]) {        	
            var reader = new FileReader();
            reader.onload = function (e) { 
            	$('#img_avatar').attr('src', e.target.result);              
            };
            reader.readAsDataURL(input.files[0]);
        }
    }             
  </script>
  
</html>

templates/form.html
{% load cropping thumbnail %}
{% load thumbnail %}

<div class="container" style="margin-top: 20px;">
	<div class="jumbotron">
		<form method="post" id="cropping_form" class="cropping_form" action="." enctype="multipart/form-data">
			{% csrf_token %}
			<table>
				<tr>
					<th>{{ form.as_p }} {{ form.media }}</th>
					<th><img src="{% thumbnail image.image_field 300x300 box=image.cropping_free %}" style="margin-left: 20px;"></th>
				</tr>
				{% if image %}
				<tr>
					<th>
						<button type="submit" class="btn btn-danger">
							<i class="fa fa-scissors"></i> Recortar
						</button>
					</th>
					<th>
						<button id="bt_form" formmethod="post" formaction="/send_file/{{ image.id }}/" formenctype="multipart/form-data" type="submit" class="btn btn-success" style="margin-left: 20px;">
							<i class="fa fa-floppy-o"></i> Salvar
						</button>
					</th>
				</tr>
				{% endif %}
			</table>
		</form>
	</div>
</div>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container" style="margin-top: 20px;">
	
 	<div class="jumbotron">
		 <form class="form-horizontal" role="form" action="." method="post" enctype="multipart/form-data">
		 {% csrf_token %}
		 {{ form.media }}
		 {{ form.as_p }}       
			<button type="submit" class="btn btn-primary"> Salvar </button>
		     <a href="/modelform_example/" class="btn btn-primary" >Show Alert</a>
		     <a href="/logout/" class="btn btn-primary" data-ajax="true" data-success="test_post">Logout</a>		        
		 </form>
	</div>  
</div> 

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="margin-top: 40px">
	<div class="row">
		<div class="col-sm-6 col-md-4 col-md-offset-4">
		{% if form.errors %}
		<div class="alert alert-danger alert-dismissible" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  {{ form.non_field_errors }}
		</div>
		{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<strong>Faça seu Login</strong>
				</div>
				<div class="panel-body">
					<form role="form" action="." method="POST">
						{% csrf_token %}
						<fieldset>
							<div class="row">
								<div class="col-sm-12 col-md-10  col-md-offset-1 ">
									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon"> <i	class="glyphicon glyphicon-user"></i></span> 
											{{ form.username }}
										</div>
									</div>
									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon"> <i class="glyphicon glyphicon-lock"></i></span> 
											{{ form.password }}
										</div>
									</div>
									<div class="form-group">
										<input type="submit" class="btn btn-lg btn-primary btn-block" value="Entrar">
									</div>
								</div>
							</div>
						</fieldset>
					</form>
				</div>
				<div class="panel-footer ">
					Não tem uma conta! <a href="/register/" onClick=""> Inscreva-se aqui </a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/modelform_example.html
{% extends "base.html" %}

{% block content %}

            <button type="button" class="btn btn-dark btn-lg" data-toggle="modal" data-target="#myModal">
            <i class="fa fa-apple fa-fw"></i>
			  iPhone
			</button>

		<!-- Button trigger modal -->
		<!-- Dialog Modal -->
		<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="myModalLabel">Imagem</h4>
					</div>
					<div class="modal-body">
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div>

{% include "form.html" %}

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<div class="container" style="padding-top: 60px;">
<div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
  <h1 class="page-header">Perfil</h1>
  <div class="row">
    <form class="form-horizontal" role="form" action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}  
        
    {% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <div class="alert alert-success alert-dismissable">
	        <a class="panel-close close" data-dismiss="alert">×</a> 
	        <i class="fa fa-thumbs-up"></i>
	        {{ message }}
	      </div>
	    {% endfor %}
	</ul>
	{% endif %}
    
    <!-- left column -->
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center" style="max-width: 200px; max-height: 200px;">
      	{% if profile.image_field %}
      		<img id="img_avatar" src="{{ profile.image_field.url }}" class="avatar img-circle img-thumbnail" alt="avatar">
      	{% else %}
      		<img id="img_avatar" src="{% static "images/mystery-avatar2.png" %}" class="avatar img-circle img-thumbnail" alt="avatar">
      	{% endif %}        
        <h6>Escolha uma foto...</h6> 
         {{ prof_form.image_field.errors }}
         {{ prof_form.image_field }}  
      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
    {% if not profile %}
       <div class="alert alert-info alert-dismissable">
        <a class="panel-close close" data-dismiss="alert">×</a> 
        <i class="fa fa-coffee"></i>
        Termine de preencher seu perfil.
      </div>
    {% endif %}
      <h3>Informação pessoal</h3>
  
        <div class="form-group">
          <label class="col-lg-3 control-label">Nome:</label>
          <div class="col-lg-8">
          	{{ user_form.first_name.errors }}
          	{{ user_form.first_name }}
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Sobrenome:</label>
          <div class="col-lg-8">
          	{{ user_form.last_name.errors }}
            {{ user_form.last_name }}
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Endereço:</label>
          <div class="col-lg-8">
			 <table>
		  		<tr>
		  		{{ prof_form.media }}
		  		{{ prof_form.address.errors }}
				{{ prof_form.address }}
		  		</tr>
			</table>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Telefone:</label>
          <div class="col-lg-8">
          	 {{ prof_form.phone.errors }}
             {{ prof_form.phone }}
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Nascimento:</label>
          <div class="col-lg-8">
          	 {{ prof_form.birthday.errors }}
             {{ prof_form.birthday }}
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">E-mail:</label>
          <div class="col-lg-8">
          	{{ user_form.email.errors }}
            {{ user_form.email }}
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
          	<button type="submit" class="btn btn-primary"> Salvar </button>
            <span></span>
            <button formaction="/" class="btn btn-default"> Cancelar </button>
          </div>
        </div>      
    </div>
    </form>
  </div>
 </div>
</div>

{% endblock %}

templates/sucesso.html
{% extends "base.html" %}
{% load staticfiles %}
{% load cropping thumbnail %}
{% load thumbnail %}

{% block content %}
<div class="container" style="margin-top: 20px;">
 	<div class="jumbotron">
	<img src="{% thumbnail image.image_field 500x500 box=image.cropping_free %}" style="margin-left: 20px;">
	</div>  
</div> 
{% endblock %}

  <script type="text/javascript">
 	//Stle for input file
  	$(":file").filestyle({buttonBefore: true, buttonName: "btn-primary", buttonText: "Adicionar Imagem"});
  	//Function for input file
 	function readURL(input) {
  		
        if (input.files && input.files[0]) {        	
            var reader = new FileReader();
           /*  var form = $('form').serialize(); */
            reader.onload = function (e) { 
                $('#blah').attr('src', e.target.result);
                //Botton show 
                btanex.style.display = "list-item";
              /*  $.post("/modelform_example/", form).success(function(data) { console.log(data.content) }); */
                            
                var form = $('form').serialize(); 
                var file = $('#id_image_field').get(0).files[0];
                
                // Criaremos um formulário
                var f = new FormData();
                // Passando o arquivo para o formulário
                f.append("form", form);
                f.append("file", file);

                var request = new XMLHttpRequest();
                request.open("POST", "/modelform_example/", true);
                request.send(f);
                
                $.ajax({
                	headers: { 
                        Accept : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
                    },
                    type: "POST",
                    url: "/modelform_example/",
                    data: form,
                    success: function (data) {
                    	alert(file.name);
                        $("/modelform_example/").html(data);
                    },
                    error: function(data) {
                        $("/modelform_example/").html("Something went wrong!");
                    }
                });
              
            };
            reader.readAsDataURL(input.files[0]);
        }
                
    }
 	
  </script>